# Generated by Django 2.0.5 on 2018-06-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rival_name', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('game_date', models.DateTimeField()),
                ('point_gain', models.IntegerField()),
                ('point_reduce', models.IntegerField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('home', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='rival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rival', to='record.Rival'),
        ),
    ]
