# Generated by Django 2.0.5 on 2018-06-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20180604_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
