# Generated by Django 2.0.5 on 2018-06-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20180604_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
