# Generated by Django 2.0.5 on 2018-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_stats_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rival',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
