# Generated by Django 2.0.5 on 2018-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20180619_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='dribble',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='tuckle',
            field=models.IntegerField(default=0),
        ),
    ]
