# Generated by Django 2.0.5 on 2018-06-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20180619_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='dribble',
            new_name='dribbles',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='remarks',
            new_name='remark',
        ),
    ]
